#const libName* = "ftd2xx64.dll"
const libName* = "ftd2xx.dll"

const 
  MAX_DESCRIPTION_SIZE* = 256

type
  FTDeviceStatus* = enum
    FT_OK,
    FT_INVALID_HANDLE,
    FT_DEVICE_NOT_FOUND,
    FT_DEVICE_NOT_OPENED,
    FT_IO_ERROR,
    FT_INSUFFICIENT_RESOURCES,
    FT_INVALID_PARAMETER,
    FT_INVALID_BAUD_RATE,   
    FT_DEVICE_NOT_OPENED_FOR_ERASE,
    FT_DEVICE_NOT_OPENED_FOR_WRITE,
    FT_FAILED_TO_WRITE_DEVICE,
    FT_EEPROM_READ_FAILED,
    FT_EEPROM_WRITE_FAILED,
    FT_EEPROM_ERASE_FAILED,
    FT_EEPROM_NOT_PRESENT,
    FT_EEPROM_NOT_PROGRAMMED,
    FT_INVALID_ARGS,
    FT_NOT_SUPPORTED,
    FT_OTHER_ERROR,
    FT_DEVICE_LIST_NOT_READY
  

type
  FTDeviceType* = enum
    FT_DEVICE_BM,
    FT_DEVICE_AM,
    FT_DEVICE_100AX,
    FT_DEVICE_UNKNOWN,
    FT_DEVICE_2232C,
    FT_DEVICE_232R,
    FT_DEVICE_2232H,
    FT_DEVICE_4232H,
    FT_DEVICE_232H,
    FT_DEVICE_X_SERIES,
    FT_DEVICE_4222H_0,
    FT_DEVICE_4222H_1_2,
    FT_DEVICE_4222H_3,
    FT_DEVICE_4222_PROG,
    FT_DEVICE_900,
    FT_DEVICE_930,
    FT_DEVICE_UMFTPD3A

### FT_OpenEx Flags
const
  FT_OPEN_BY_SERIAL_NUMBER* = 1
  FT_OPEN_BY_DESCRIPTION* = 2
  FT_OPEN_BY_LOCATION* = 4

# FT_ListDevices Flags (used in conjunction with FT_OpenEx Flags
#
const
  FT_LIST_NUMBER_ONLY*     = 0x80000000
  FT_LIST_BY_INDEX*        = 0x40000000
  FT_LIST_ALL*             = 0x20000000


# Purge rx and tx buffers
#
const 
  FT_PURGE_RX* = 1
  FT_PURGE_TX* = 2